spring.application.name=SpringBasics
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/oms
spring.datasource.username=root
spring.datasource.password=Welcome@123a
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

com.tek.cors.url=http://localhost:3000